/**
 * Created by diman on 01.06.17.
 */


export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const GET_CATALOG_SUCCESS = "GET_CATALOG_SUCCESS";
export const GET_CATALOG_SHOP_SUCCESS = "GET_CATALOG_SHOP_SUCCESS";
export const GET_OPERATIONS_SUCCESS = "GET_OPERATIONS_SUCCESS";
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS";
export const POST_CARDS_SUCCESS = "POST_CARDS_SUCCESS";
export const GET_RIGHT_BLOCK_SUCCESS = "GET_RIGHT_BLOCK_SUCCESS";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";